# data-www
data-www:
    container_name: ${PROJECT_NAME}_data-www
    image: busybox
    volumes:
        - ./app:/app

## php-fpm
php-fpm:
    container_name: ${PROJECT_NAME}_php-fpm
    build: ./docker-assets/php-fpm
    volumes_from:
        - data-www
    volumes:
        - ./docker-assets/php-fpm/scripts:/scripts
    links:
        - mysql
        - redis
    working_dir: /app
    environment:
        REDIS_PORT: 

# nginx
nginx:
    container_name: ${PROJECT_NAME}_nginx
    build: ./docker-assets/nginx
    volumes_from:
        - data-www
    volumes:
        # - ./swagger:/swagger
        - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
    links:
        - php-fpm
        # - node
    ports:
        - "8080:8080"
        - "443:443"
    working_dir: /app

# mysql
mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql
    volumes:
        - ./docker-assets/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        - ./mysql_data:/var/lib/mysql
    ports:
         - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret

## redis
redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:alpine

# ## node
# node:
#     container_name: ${PROJECT_NAME}_node
#     image: node
#     volumes:
#         - ./docker-assets/node/scripts:/scripts
#         - ./node:/app
#     links:
#         - mysql
#     working_dir: /app
#     entrypoint: /scripts/bootstrap.sh
